# Generated by Django 5.2.13 on 2026-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
