# Generated by Django 5.2.13 on 2026-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_location_name_alter_searchlog_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterModelTable(
            name='searchlog',
            table=None,
        ),
    ]
